name: Generate docs and format

on: push

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To get all tags
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: nvim-texlabconfig
          pandoc: "README.md"
          version: "NVIM 0.10.4"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(docs): auto generate docs"
          branch: ${{ github.head_ref }}

      - name: "Format with Stylua"
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.15.1
          args: .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(format): format with stylua"
          branch: ${{ github.head_ref }}
